[2025-04-18T21:24:31.667+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T21:24:31.698+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T21:24:31.713+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T21:24:31.714+0000] {taskinstance.py:2867} INFO - Starting attempt 25 of 26
[2025-04-18T21:24:31.732+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_all_models> on 2025-04-18 19:56:57.798037+00:00
[2025-04-18T21:24:31.741+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_dbt', 'run_dbt_all_models', 'manual__2025-04-18T19:56:57.798037+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_model.py', '--cfg-path', '/tmp/tmp_dt546kq']
[2025-04-18T21:24:31.744+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=48245) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T21:24:31.745+0000] {standard_task_runner.py:105} INFO - Job 659: Subtask run_dbt_all_models
[2025-04-18T21:24:31.746+0000] {standard_task_runner.py:72} INFO - Started process 48246 to run task
[2025-04-18T21:24:31.803+0000] {task_command.py:467} INFO - Running <TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [running]> on host f21ba0bbe878
[2025-04-18T21:24:31.908+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_dbt' AIRFLOW_CTX_TASK_ID='run_dbt_all_models' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T19:56:57.798037+00:00' AIRFLOW_CTX_TRY_NUMBER='25' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T19:56:57.798037+00:00'
[2025-04-18T21:24:31.909+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T21:24:31.933+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T21:24:31.935+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2025-04-18T21:24:31.947+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T21:24:36.413+0000] {subprocess.py:106} INFO - [0m21:24:36  Running with dbt=1.8.1
[2025-04-18T21:24:39.084+0000] {subprocess.py:106} INFO - [0m21:24:39  Registered adapter: bigquery=1.8.1
[2025-04-18T21:24:42.426+0000] {subprocess.py:106} INFO - [0m21:24:42  Found 1 seed, 10 models, 1 source, 602 macros
[2025-04-18T21:24:42.433+0000] {subprocess.py:106} INFO - [0m21:24:42
[2025-04-18T21:24:43.345+0000] {subprocess.py:106} INFO - [0m21:24:43  Concurrency: 1 threads (target='dev')
[2025-04-18T21:24:43.346+0000] {subprocess.py:106} INFO - [0m21:24:43
[2025-04-18T21:24:43.364+0000] {subprocess.py:106} INFO - [0m21:24:43  1 of 10 START sql table model db_project_dataset.dim_airports .................. [RUN]
[2025-04-18T21:24:45.925+0000] {subprocess.py:106} INFO - [0m21:24:45  1 of 10 OK created sql table model db_project_dataset.dim_airports ............. [[32mCREATE TABLE (3.4k rows, 141.3 KiB processed)[0m in 2.56s]
[2025-04-18T21:24:45.928+0000] {subprocess.py:106} INFO - [0m21:24:45  2 of 10 START sql view model db_project_dataset.stg_flights .................... [RUN]
[2025-04-18T21:24:46.687+0000] {subprocess.py:106} INFO - [0m21:24:46  2 of 10 OK created sql view model db_project_dataset.stg_flights ............... [[32mCREATE VIEW (0 processed)[0m in 0.76s]
[2025-04-18T21:24:46.694+0000] {subprocess.py:106} INFO - [0m21:24:46  3 of 10 START sql table model db_project_dataset.core_flights .................. [RUN]
[2025-04-18T21:24:52.526+0000] {subprocess.py:106} INFO - [0m21:24:52  3 of 10 OK created sql table model db_project_dataset.core_flights ............. [[32mCREATE TABLE (112.3m rows, 11.7 GiB processed)[0m in 5.83s]
[2025-04-18T21:24:52.536+0000] {subprocess.py:106} INFO - [0m21:24:52  4 of 10 START sql table model db_project_dataset.dim_carriers .................. [RUN]
[2025-04-18T21:24:54.766+0000] {subprocess.py:106} INFO - [0m21:24:54  4 of 10 OK created sql table model db_project_dataset.dim_carriers ............. [[32mCREATE TABLE (29.0 rows, 3.9 GiB processed)[0m in 2.23s]
[2025-04-18T21:24:54.773+0000] {subprocess.py:106} INFO - [0m21:24:54  5 of 10 START sql table model db_project_dataset.dim_dates ..................... [RUN]
[2025-04-18T21:24:56.878+0000] {subprocess.py:106} INFO - [0m21:24:56  5 of 10 OK created sql table model db_project_dataset.dim_dates ................ [[32mCREATE TABLE (7.4k rows, 857.0 MiB processed)[0m in 2.10s]
[2025-04-18T21:24:56.882+0000] {subprocess.py:106} INFO - [0m21:24:56  6 of 10 START sql table model db_project_dataset.fact_delays_by_flight_num ..... [RUN]
[2025-04-18T21:25:00.269+0000] {subprocess.py:106} INFO - [0m21:25:00  6 of 10 OK created sql table model db_project_dataset.fact_delays_by_flight_num  [[32mCREATE TABLE (8.1k rows, 2.5 GiB processed)[0m in 3.38s]
[2025-04-18T21:25:00.273+0000] {subprocess.py:106} INFO - [0m21:25:00  7 of 10 START sql table model db_project_dataset.fact_delays_departure_by_airport  [RUN]
[2025-04-18T21:25:02.446+0000] {subprocess.py:106} INFO - [0m21:25:02  7 of 10 OK created sql table model db_project_dataset.fact_delays_departure_by_airport  [[32mCREATE TABLE (1.3k rows, 4.1 GiB processed)[0m in 2.17s]
[2025-04-18T21:25:02.452+0000] {subprocess.py:106} INFO - [0m21:25:02  8 of 10 START sql table model db_project_dataset.fact_departures.by_year ....... [RUN]
[2025-04-18T21:25:03.477+0000] {subprocess.py:106} INFO - [0m21:25:03  BigQuery adapter: https://console.cloud.google.com/bigquery?project=db-project-456518&j=bq:europe-central2:eeaa7e76-a838-4803-9119-db3a40c00319&page=queryresults
[2025-04-18T21:25:03.502+0000] {subprocess.py:106} INFO - [0m21:25:03  8 of 10 ERROR creating sql table model db_project_dataset.fact_departures.by_year  [[31mERROR[0m in 1.04s]
[2025-04-18T21:25:03.524+0000] {subprocess.py:106} INFO - [0m21:25:03  9 of 10 START sql table model db_project_dataset.fact_departures_by_airport_year  [RUN]
[2025-04-18T21:25:05.728+0000] {subprocess.py:106} INFO - [0m21:25:05  9 of 10 OK created sql table model db_project_dataset.fact_departures_by_airport_year  [[32mCREATE TABLE (343.0 rows, 535.6 MiB processed)[0m in 2.20s]
[2025-04-18T21:25:05.733+0000] {subprocess.py:106} INFO - [0m21:25:05  10 of 10 START sql table model db_project_dataset.fact_most_departures_airport . [RUN]
[2025-04-18T21:25:07.891+0000] {subprocess.py:106} INFO - [0m21:25:07  10 of 10 OK created sql table model db_project_dataset.fact_most_departures_airport  [[32mCREATE TABLE (352.0 rows, 2.7 GiB processed)[0m in 2.15s]
[2025-04-18T21:25:07.903+0000] {subprocess.py:106} INFO - [0m21:25:07
[2025-04-18T21:25:07.905+0000] {subprocess.py:106} INFO - [0m21:25:07  Finished running 9 table models, 1 view model in 0 hours 0 minutes and 25.47 seconds (25.47s).
[2025-04-18T21:25:08.051+0000] {subprocess.py:106} INFO - [0m21:25:08
[2025-04-18T21:25:08.054+0000] {subprocess.py:106} INFO - [0m21:25:08  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-18T21:25:08.056+0000] {subprocess.py:106} INFO - [0m21:25:08
[2025-04-18T21:25:08.058+0000] {subprocess.py:106} INFO - [0m21:25:08    Database Error in model fact_departures.by_year (models/marts/fact_departures.by_year.sql)
[2025-04-18T21:25:08.059+0000] {subprocess.py:106} INFO -   Invalid project ID 'db-project-456518.db_project_dataset'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[2025-04-18T21:25:08.060+0000] {subprocess.py:106} INFO -   compiled code at target/run/flights_project/models/marts/fact_departures.by_year.sql
[2025-04-18T21:25:08.060+0000] {subprocess.py:106} INFO - [0m21:25:08
[2025-04-18T21:25:08.061+0000] {subprocess.py:106} INFO - [0m21:25:08  Done. PASS=9 WARN=0 ERROR=1 SKIP=0 TOTAL=10
[2025-04-18T21:25:09.369+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-18T21:25:09.381+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T21:25:09.390+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=run_dbt, task_id=run_dbt_all_models, run_id=manual__2025-04-18T19:56:57.798037+00:00, execution_date=20250418T195657, start_date=20250418T212431, end_date=20250418T212509
[2025-04-18T21:25:09.425+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T21:25:09.426+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 659 for task run_dbt_all_models (Bash command failed. The command returned a non-zero exit code 1.; 48246)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T21:25:09.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T21:25:09.496+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T21:25:09.499+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
