[2025-04-18T21:26:03.038+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T21:26:03.061+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T21:26:03.075+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T21:26:03.076+0000] {taskinstance.py:2867} INFO - Starting attempt 26 of 27
[2025-04-18T21:26:03.090+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_all_models> on 2025-04-18 19:56:57.798037+00:00
[2025-04-18T21:26:03.101+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=48398) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T21:26:03.100+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_dbt', 'run_dbt_all_models', 'manual__2025-04-18T19:56:57.798037+00:00', '--job-id', '662', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_model.py', '--cfg-path', '/tmp/tmpp97v9wav']
[2025-04-18T21:26:03.102+0000] {standard_task_runner.py:72} INFO - Started process 48399 to run task
[2025-04-18T21:26:03.102+0000] {standard_task_runner.py:105} INFO - Job 662: Subtask run_dbt_all_models
[2025-04-18T21:26:03.151+0000] {task_command.py:467} INFO - Running <TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [running]> on host f21ba0bbe878
[2025-04-18T21:26:03.232+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_dbt' AIRFLOW_CTX_TASK_ID='run_dbt_all_models' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T19:56:57.798037+00:00' AIRFLOW_CTX_TRY_NUMBER='26' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T19:56:57.798037+00:00'
[2025-04-18T21:26:03.233+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T21:26:03.248+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T21:26:03.251+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2025-04-18T21:26:03.259+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T21:26:06.018+0000] {subprocess.py:106} INFO - [0m21:26:06  Running with dbt=1.8.1
[2025-04-18T21:26:07.433+0000] {subprocess.py:106} INFO - [0m21:26:07  Registered adapter: bigquery=1.8.1
[2025-04-18T21:26:09.008+0000] {subprocess.py:106} INFO - [0m21:26:09  Found 1 seed, 10 models, 1 source, 602 macros
[2025-04-18T21:26:09.013+0000] {subprocess.py:106} INFO - [0m21:26:09
[2025-04-18T21:26:09.675+0000] {subprocess.py:106} INFO - [0m21:26:09  Concurrency: 1 threads (target='dev')
[2025-04-18T21:26:09.676+0000] {subprocess.py:106} INFO - [0m21:26:09
[2025-04-18T21:26:09.688+0000] {subprocess.py:106} INFO - [0m21:26:09  1 of 10 START sql table model db_project_dataset.dim_airports .................. [RUN]
[2025-04-18T21:26:11.905+0000] {subprocess.py:106} INFO - [0m21:26:11  1 of 10 OK created sql table model db_project_dataset.dim_airports ............. [[32mCREATE TABLE (3.4k rows, 141.3 KiB processed)[0m in 2.21s]
[2025-04-18T21:26:11.911+0000] {subprocess.py:106} INFO - [0m21:26:11  2 of 10 START sql view model db_project_dataset.stg_flights .................... [RUN]
[2025-04-18T21:26:12.619+0000] {subprocess.py:106} INFO - [0m21:26:12  2 of 10 OK created sql view model db_project_dataset.stg_flights ............... [[32mCREATE VIEW (0 processed)[0m in 0.70s]
[2025-04-18T21:26:12.625+0000] {subprocess.py:106} INFO - [0m21:26:12  3 of 10 START sql table model db_project_dataset.core_flights .................. [RUN]
[2025-04-18T21:26:17.720+0000] {subprocess.py:106} INFO - [0m21:26:17  3 of 10 OK created sql table model db_project_dataset.core_flights ............. [[32mCREATE TABLE (112.3m rows, 11.7 GiB processed)[0m in 5.09s]
[2025-04-18T21:26:17.728+0000] {subprocess.py:106} INFO - [0m21:26:17  4 of 10 START sql table model db_project_dataset.dim_carriers .................. [RUN]
[2025-04-18T21:26:19.869+0000] {subprocess.py:106} INFO - [0m21:26:19  4 of 10 OK created sql table model db_project_dataset.dim_carriers ............. [[32mCREATE TABLE (29.0 rows, 3.9 GiB processed)[0m in 2.14s]
[2025-04-18T21:26:19.876+0000] {subprocess.py:106} INFO - [0m21:26:19  5 of 10 START sql table model db_project_dataset.dim_dates ..................... [RUN]
[2025-04-18T21:26:21.988+0000] {subprocess.py:106} INFO - [0m21:26:21  5 of 10 OK created sql table model db_project_dataset.dim_dates ................ [[32mCREATE TABLE (7.4k rows, 857.0 MiB processed)[0m in 2.11s]
[2025-04-18T21:26:21.993+0000] {subprocess.py:106} INFO - [0m21:26:21  6 of 10 START sql table model db_project_dataset.fact_delays_by_flight_num ..... [RUN]
[2025-04-18T21:26:24.181+0000] {subprocess.py:106} INFO - [0m21:26:24  6 of 10 OK created sql table model db_project_dataset.fact_delays_by_flight_num  [[32mCREATE TABLE (8.1k rows, 2.5 GiB processed)[0m in 2.18s]
[2025-04-18T21:26:24.186+0000] {subprocess.py:106} INFO - [0m21:26:24  7 of 10 START sql table model db_project_dataset.fact_delays_departure_by_airport  [RUN]
[2025-04-18T21:26:26.329+0000] {subprocess.py:106} INFO - [0m21:26:26  7 of 10 OK created sql table model db_project_dataset.fact_delays_departure_by_airport  [[32mCREATE TABLE (1.3k rows, 4.1 GiB processed)[0m in 2.13s]
[2025-04-18T21:26:26.343+0000] {subprocess.py:106} INFO - [0m21:26:26  8 of 10 START sql table model db_project_dataset.fact_departures.by_year ....... [RUN]
[2025-04-18T21:26:26.899+0000] {subprocess.py:106} INFO - [0m21:26:26  BigQuery adapter: https://console.cloud.google.com/bigquery?project=db-project-456518&j=bq:europe-central2:b17c5fbe-359d-435b-998b-19bf2c87d68c&page=queryresults
[2025-04-18T21:26:26.914+0000] {subprocess.py:106} INFO - [0m21:26:26  8 of 10 ERROR creating sql table model db_project_dataset.fact_departures.by_year  [[31mERROR[0m in 0.56s]
[2025-04-18T21:26:26.919+0000] {subprocess.py:106} INFO - [0m21:26:26  9 of 10 START sql table model db_project_dataset.fact_departures_by_airport_year  [RUN]
[2025-04-18T21:26:29.022+0000] {subprocess.py:106} INFO - [0m21:26:29  9 of 10 OK created sql table model db_project_dataset.fact_departures_by_airport_year  [[32mCREATE TABLE (343.0 rows, 535.6 MiB processed)[0m in 2.10s]
[2025-04-18T21:26:29.028+0000] {subprocess.py:106} INFO - [0m21:26:29  10 of 10 START sql table model db_project_dataset.fact_most_departures_airport . [RUN]
[2025-04-18T21:26:31.206+0000] {subprocess.py:106} INFO - [0m21:26:31  10 of 10 OK created sql table model db_project_dataset.fact_most_departures_airport  [[32mCREATE TABLE (352.0 rows, 2.7 GiB processed)[0m in 2.17s]
[2025-04-18T21:26:31.215+0000] {subprocess.py:106} INFO - [0m21:26:31
[2025-04-18T21:26:31.217+0000] {subprocess.py:106} INFO - [0m21:26:31  Finished running 9 table models, 1 view model in 0 hours 0 minutes and 22.20 seconds (22.20s).
[2025-04-18T21:26:31.371+0000] {subprocess.py:106} INFO - [0m21:26:31
[2025-04-18T21:26:31.372+0000] {subprocess.py:106} INFO - [0m21:26:31  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-18T21:26:31.373+0000] {subprocess.py:106} INFO - [0m21:26:31
[2025-04-18T21:26:31.375+0000] {subprocess.py:106} INFO - [0m21:26:31    Database Error in model fact_departures.by_year (models/marts/fact_departures.by_year.sql)
[2025-04-18T21:26:31.375+0000] {subprocess.py:106} INFO -   Invalid project ID 'db-project-456518.db_project_dataset'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[2025-04-18T21:26:31.376+0000] {subprocess.py:106} INFO -   compiled code at target/run/flights_project/models/marts/fact_departures.by_year.sql
[2025-04-18T21:26:31.376+0000] {subprocess.py:106} INFO - [0m21:26:31
[2025-04-18T21:26:31.377+0000] {subprocess.py:106} INFO - [0m21:26:31  Done. PASS=9 WARN=0 ERROR=1 SKIP=0 TOTAL=10
[2025-04-18T21:26:32.518+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-18T21:26:32.530+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T21:26:32.541+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=run_dbt, task_id=run_dbt_all_models, run_id=manual__2025-04-18T19:56:57.798037+00:00, execution_date=20250418T195657, start_date=20250418T212603, end_date=20250418T212632
[2025-04-18T21:26:32.577+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T21:26:32.578+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 662 for task run_dbt_all_models (Bash command failed. The command returned a non-zero exit code 1.; 48399)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T21:26:32.599+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T21:26:32.622+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T21:26:32.625+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
