[2025-04-18T22:04:44.598+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T22:04:44.638+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T22:04:44.658+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T22:04:44.659+0000] {taskinstance.py:2867} INFO - Starting attempt 31 of 32
[2025-04-18T22:04:44.681+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_all_models> on 2025-04-18 19:56:57.798037+00:00
[2025-04-18T22:04:44.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_dbt', 'run_dbt_all_models', 'manual__2025-04-18T19:56:57.798037+00:00', '--job-id', '667', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_model.py', '--cfg-path', '/tmp/tmpu5627wea']
[2025-04-18T22:04:44.694+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=50844) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T22:04:44.695+0000] {standard_task_runner.py:105} INFO - Job 667: Subtask run_dbt_all_models
[2025-04-18T22:04:44.695+0000] {standard_task_runner.py:72} INFO - Started process 50849 to run task
[2025-04-18T22:04:44.753+0000] {task_command.py:467} INFO - Running <TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [running]> on host f21ba0bbe878
[2025-04-18T22:04:44.856+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_dbt' AIRFLOW_CTX_TASK_ID='run_dbt_all_models' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T19:56:57.798037+00:00' AIRFLOW_CTX_TRY_NUMBER='31' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T19:56:57.798037+00:00'
[2025-04-18T22:04:44.857+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T22:04:44.878+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T22:04:44.880+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2025-04-18T22:04:44.892+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T22:04:47.975+0000] {subprocess.py:106} INFO - [0m22:04:47  Running with dbt=1.8.1
[2025-04-18T22:04:51.487+0000] {subprocess.py:106} INFO - [0m22:04:51  Registered adapter: bigquery=1.8.1
[2025-04-18T22:04:54.376+0000] {subprocess.py:106} INFO - [0m22:04:54  Found 1 seed, 10 models, 1 source, 602 macros
[2025-04-18T22:04:54.384+0000] {subprocess.py:106} INFO - [0m22:04:54
[2025-04-18T22:04:55.020+0000] {subprocess.py:106} INFO - [0m22:04:55  Concurrency: 1 threads (target='dev')
[2025-04-18T22:04:55.021+0000] {subprocess.py:106} INFO - [0m22:04:55
[2025-04-18T22:04:55.037+0000] {subprocess.py:106} INFO - [0m22:04:55  1 of 10 START sql table model db_project_dataset.dim_airports .................. [RUN]
[2025-04-18T22:04:57.332+0000] {subprocess.py:106} INFO - [0m22:04:57  1 of 10 OK created sql table model db_project_dataset.dim_airports ............. [[32mCREATE TABLE (3.4k rows, 141.3 KiB processed)[0m in 2.29s]
[2025-04-18T22:04:57.337+0000] {subprocess.py:106} INFO - [0m22:04:57  2 of 10 START sql view model db_project_dataset.stg_flights .................... [RUN]
[2025-04-18T22:04:57.971+0000] {subprocess.py:106} INFO - [0m22:04:57  2 of 10 OK created sql view model db_project_dataset.stg_flights ............... [[32mCREATE VIEW (0 processed)[0m in 0.63s]
[2025-04-18T22:04:57.976+0000] {subprocess.py:106} INFO - [0m22:04:57  3 of 10 START sql table model db_project_dataset.core_flights .................. [RUN]
[2025-04-18T22:05:04.119+0000] {subprocess.py:106} INFO - [0m22:05:04  3 of 10 OK created sql table model db_project_dataset.core_flights ............. [[32mCREATE TABLE (112.3m rows, 11.7 GiB processed)[0m in 6.14s]
[2025-04-18T22:05:04.125+0000] {subprocess.py:106} INFO - [0m22:05:04  4 of 10 START sql table model db_project_dataset.dim_carriers .................. [RUN]
[2025-04-18T22:05:06.238+0000] {subprocess.py:106} INFO - [0m22:05:06  4 of 10 OK created sql table model db_project_dataset.dim_carriers ............. [[32mCREATE TABLE (29.0 rows, 3.9 GiB processed)[0m in 2.11s]
[2025-04-18T22:05:06.243+0000] {subprocess.py:106} INFO - [0m22:05:06  5 of 10 START sql table model db_project_dataset.dim_dates ..................... [RUN]
[2025-04-18T22:05:08.314+0000] {subprocess.py:106} INFO - [0m22:05:08  5 of 10 OK created sql table model db_project_dataset.dim_dates ................ [[32mCREATE TABLE (7.4k rows, 857.0 MiB processed)[0m in 2.07s]
[2025-04-18T22:05:08.319+0000] {subprocess.py:106} INFO - [0m22:05:08  6 of 10 START sql table model db_project_dataset.fact_delays_by_flight_num ..... [RUN]
[2025-04-18T22:05:10.689+0000] {subprocess.py:106} INFO - [0m22:05:10  6 of 10 OK created sql table model db_project_dataset.fact_delays_by_flight_num  [[32mCREATE TABLE (8.1k rows, 2.5 GiB processed)[0m in 2.36s]
[2025-04-18T22:05:10.708+0000] {subprocess.py:106} INFO - [0m22:05:10  7 of 10 START sql table model db_project_dataset.fact_departure_delays_by_airport  [RUN]
[2025-04-18T22:05:11.712+0000] {subprocess.py:106} INFO - [0m22:05:11  BigQuery adapter: https://console.cloud.google.com/bigquery?project=db-project-456518&j=bq:europe-central2:c1d81f8f-0c67-4e72-a3c8-3e9152a97a6e&page=queryresults
[2025-04-18T22:05:11.727+0000] {subprocess.py:106} INFO - [0m22:05:11  7 of 10 ERROR creating sql table model db_project_dataset.fact_departure_delays_by_airport  [[31mERROR[0m in 1.02s]
[2025-04-18T22:05:11.732+0000] {subprocess.py:106} INFO - [0m22:05:11  8 of 10 START sql table model db_project_dataset.fact_departures_by_airport_year  [RUN]
[2025-04-18T22:05:14.531+0000] {subprocess.py:106} INFO - [0m22:05:14  8 of 10 OK created sql table model db_project_dataset.fact_departures_by_airport_year  [[32mCREATE TABLE (343.0 rows, 535.6 MiB processed)[0m in 2.79s]
[2025-04-18T22:05:14.538+0000] {subprocess.py:106} INFO - [0m22:05:14  9 of 10 START sql table model db_project_dataset.fact_departures_yearly ........ [RUN]
[2025-04-18T22:05:16.698+0000] {subprocess.py:106} INFO - [0m22:05:16  9 of 10 OK created sql table model db_project_dataset.fact_departures_yearly ... [[32mCREATE TABLE (21.0 rows, 857.0 MiB processed)[0m in 2.16s]
[2025-04-18T22:05:16.702+0000] {subprocess.py:106} INFO - [0m22:05:16  10 of 10 START sql table model db_project_dataset.fact_most_departures_airport . [RUN]
[2025-04-18T22:05:18.740+0000] {subprocess.py:106} INFO - [0m22:05:18  10 of 10 OK created sql table model db_project_dataset.fact_most_departures_airport  [[32mCREATE TABLE (352.0 rows, 2.7 GiB processed)[0m in 2.03s]
[2025-04-18T22:05:18.747+0000] {subprocess.py:106} INFO - [0m22:05:18
[2025-04-18T22:05:18.749+0000] {subprocess.py:106} INFO - [0m22:05:18  Finished running 9 table models, 1 view model in 0 hours 0 minutes and 24.36 seconds (24.36s).
[2025-04-18T22:05:18.861+0000] {subprocess.py:106} INFO - [0m22:05:18
[2025-04-18T22:05:18.862+0000] {subprocess.py:106} INFO - [0m22:05:18  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-18T22:05:18.863+0000] {subprocess.py:106} INFO - [0m22:05:18
[2025-04-18T22:05:18.864+0000] {subprocess.py:106} INFO - [0m22:05:18    Database Error in model fact_departure_delays_by_airport (models/marts/fact_departure_delays_by_airport.sql)
[2025-04-18T22:05:18.864+0000] {subprocess.py:106} INFO -   SELECT list expression references column dep_delay which is neither grouped nor aggregated at [26:5]
[2025-04-18T22:05:18.865+0000] {subprocess.py:106} INFO -   compiled code at target/run/flights_project/models/marts/fact_departure_delays_by_airport.sql
[2025-04-18T22:05:18.865+0000] {subprocess.py:106} INFO - [0m22:05:18
[2025-04-18T22:05:18.866+0000] {subprocess.py:106} INFO - [0m22:05:18  Done. PASS=9 WARN=0 ERROR=1 SKIP=0 TOTAL=10
[2025-04-18T22:05:20.335+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-18T22:05:20.349+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T22:05:20.360+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=run_dbt, task_id=run_dbt_all_models, run_id=manual__2025-04-18T19:56:57.798037+00:00, execution_date=20250418T195657, start_date=20250418T220444, end_date=20250418T220520
[2025-04-18T22:05:20.399+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T22:05:20.400+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 667 for task run_dbt_all_models (Bash command failed. The command returned a non-zero exit code 1.; 50849)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T22:05:20.414+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T22:05:20.438+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T22:05:20.439+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
