[2025-04-18T22:03:40.063+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T22:03:40.124+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T22:03:40.157+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T22:03:40.158+0000] {taskinstance.py:2867} INFO - Starting attempt 30 of 30
[2025-04-18T22:03:40.190+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_all_models> on 2025-04-18 19:56:57.798037+00:00
[2025-04-18T22:03:40.205+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_dbt', 'run_dbt_all_models', 'manual__2025-04-18T19:56:57.798037+00:00', '--job-id', '666', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_model.py', '--cfg-path', '/tmp/tmpjshhymkk']
[2025-04-18T22:03:40.209+0000] {standard_task_runner.py:105} INFO - Job 666: Subtask run_dbt_all_models
[2025-04-18T22:03:40.229+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=50743) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T22:03:40.230+0000] {standard_task_runner.py:72} INFO - Started process 50760 to run task
[2025-04-18T22:03:40.377+0000] {task_command.py:467} INFO - Running <TaskInstance: run_dbt.run_dbt_all_models manual__2025-04-18T19:56:57.798037+00:00 [running]> on host f21ba0bbe878
[2025-04-18T22:03:41.023+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_dbt' AIRFLOW_CTX_TASK_ID='run_dbt_all_models' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T19:56:57.798037+00:00' AIRFLOW_CTX_TRY_NUMBER='30' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T19:56:57.798037+00:00'
[2025-04-18T22:03:41.024+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T22:03:41.071+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T22:03:41.073+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2025-04-18T22:03:41.095+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T22:03:46.058+0000] {subprocess.py:106} INFO - [0m22:03:46  Running with dbt=1.8.1
[2025-04-18T22:03:49.000+0000] {subprocess.py:106} INFO - [0m22:03:48  Registered adapter: bigquery=1.8.1
[2025-04-18T22:03:51.608+0000] {subprocess.py:106} INFO - [0m22:03:51  Found 1 seed, 10 models, 1 source, 602 macros
[2025-04-18T22:03:51.615+0000] {subprocess.py:106} INFO - [0m22:03:51
[2025-04-18T22:03:52.722+0000] {subprocess.py:106} INFO - [0m22:03:52  Concurrency: 1 threads (target='dev')
[2025-04-18T22:03:52.724+0000] {subprocess.py:106} INFO - [0m22:03:52
[2025-04-18T22:03:54.479+0000] {subprocess.py:106} INFO - [0m22:03:54  1 of 10 START sql table model db_project_dataset.dim_airports .................. [RUN]
[2025-04-18T22:03:56.504+0000] {subprocess.py:106} INFO - [0m22:03:56  1 of 10 OK created sql table model db_project_dataset.dim_airports ............. [[32mCREATE TABLE (3.4k rows, 141.3 KiB processed)[0m in 2.01s]
[2025-04-18T22:03:56.510+0000] {subprocess.py:106} INFO - [0m22:03:56  2 of 10 START sql view model db_project_dataset.stg_flights .................... [RUN]
[2025-04-18T22:03:57.445+0000] {subprocess.py:106} INFO - [0m22:03:57  2 of 10 OK created sql view model db_project_dataset.stg_flights ............... [[32mCREATE VIEW (0 processed)[0m in 0.93s]
[2025-04-18T22:03:57.451+0000] {subprocess.py:106} INFO - [0m22:03:57  3 of 10 START sql table model db_project_dataset.core_flights .................. [RUN]
[2025-04-18T22:04:03.265+0000] {subprocess.py:106} INFO - [0m22:04:03  3 of 10 OK created sql table model db_project_dataset.core_flights ............. [[32mCREATE TABLE (112.3m rows, 11.7 GiB processed)[0m in 5.81s]
[2025-04-18T22:04:03.274+0000] {subprocess.py:106} INFO - [0m22:04:03  4 of 10 START sql table model db_project_dataset.dim_carriers .................. [RUN]
[2025-04-18T22:04:05.308+0000] {subprocess.py:106} INFO - [0m22:04:05  4 of 10 OK created sql table model db_project_dataset.dim_carriers ............. [[32mCREATE TABLE (29.0 rows, 3.9 GiB processed)[0m in 2.03s]
[2025-04-18T22:04:05.319+0000] {subprocess.py:106} INFO - [0m22:04:05  5 of 10 START sql table model db_project_dataset.dim_dates ..................... [RUN]
[2025-04-18T22:04:07.582+0000] {subprocess.py:106} INFO - [0m22:04:07  5 of 10 OK created sql table model db_project_dataset.dim_dates ................ [[32mCREATE TABLE (7.4k rows, 857.0 MiB processed)[0m in 2.26s]
[2025-04-18T22:04:07.587+0000] {subprocess.py:106} INFO - [0m22:04:07  6 of 10 START sql table model db_project_dataset.fact_delays_by_flight_num ..... [RUN]
[2025-04-18T22:04:10.011+0000] {subprocess.py:106} INFO - [0m22:04:10  6 of 10 OK created sql table model db_project_dataset.fact_delays_by_flight_num  [[32mCREATE TABLE (8.1k rows, 2.5 GiB processed)[0m in 2.42s]
[2025-04-18T22:04:10.016+0000] {subprocess.py:106} INFO - [0m22:04:10  7 of 10 START sql table model db_project_dataset.fact_departure_delays_by_airport  [RUN]
[2025-04-18T22:04:10.952+0000] {subprocess.py:106} INFO - [0m22:04:10  BigQuery adapter: https://console.cloud.google.com/bigquery?project=db-project-456518&j=bq:europe-central2:e6bee513-d1a3-45f3-ac41-efb981b00db7&page=queryresults
[2025-04-18T22:04:10.966+0000] {subprocess.py:106} INFO - [0m22:04:10  7 of 10 ERROR creating sql table model db_project_dataset.fact_departure_delays_by_airport  [[31mERROR[0m in 0.95s]
[2025-04-18T22:04:10.973+0000] {subprocess.py:106} INFO - [0m22:04:10  8 of 10 START sql table model db_project_dataset.fact_departures_by_airport_year  [RUN]
[2025-04-18T22:04:13.082+0000] {subprocess.py:106} INFO - [0m22:04:13  8 of 10 OK created sql table model db_project_dataset.fact_departures_by_airport_year  [[32mCREATE TABLE (343.0 rows, 535.6 MiB processed)[0m in 2.11s]
[2025-04-18T22:04:13.087+0000] {subprocess.py:106} INFO - [0m22:04:13  9 of 10 START sql table model db_project_dataset.fact_departures_yearly ........ [RUN]
[2025-04-18T22:04:15.256+0000] {subprocess.py:106} INFO - [0m22:04:15  9 of 10 OK created sql table model db_project_dataset.fact_departures_yearly ... [[32mCREATE TABLE (21.0 rows, 857.0 MiB processed)[0m in 2.17s]
[2025-04-18T22:04:15.262+0000] {subprocess.py:106} INFO - [0m22:04:15  10 of 10 START sql table model db_project_dataset.fact_most_departures_airport . [RUN]
[2025-04-18T22:04:17.508+0000] {subprocess.py:106} INFO - [0m22:04:17  10 of 10 OK created sql table model db_project_dataset.fact_most_departures_airport  [[32mCREATE TABLE (352.0 rows, 2.7 GiB processed)[0m in 2.24s]
[2025-04-18T22:04:17.515+0000] {subprocess.py:106} INFO - [0m22:04:17
[2025-04-18T22:04:17.516+0000] {subprocess.py:106} INFO - [0m22:04:17  Finished running 9 table models, 1 view model in 0 hours 0 minutes and 25.90 seconds (25.90s).
[2025-04-18T22:04:17.612+0000] {subprocess.py:106} INFO - [0m22:04:17
[2025-04-18T22:04:17.613+0000] {subprocess.py:106} INFO - [0m22:04:17  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-18T22:04:17.614+0000] {subprocess.py:106} INFO - [0m22:04:17
[2025-04-18T22:04:17.615+0000] {subprocess.py:106} INFO - [0m22:04:17    Database Error in model fact_departure_delays_by_airport (models/marts/fact_departure_delays_by_airport.sql)
[2025-04-18T22:04:17.616+0000] {subprocess.py:106} INFO -   Unrecognized name: delay_status at [30:23]
[2025-04-18T22:04:17.616+0000] {subprocess.py:106} INFO -   compiled code at target/run/flights_project/models/marts/fact_departure_delays_by_airport.sql
[2025-04-18T22:04:17.617+0000] {subprocess.py:106} INFO - [0m22:04:17
[2025-04-18T22:04:17.617+0000] {subprocess.py:106} INFO - [0m22:04:17  Done. PASS=9 WARN=0 ERROR=1 SKIP=0 TOTAL=10
[2025-04-18T22:04:19.800+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-18T22:04:19.820+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T22:04:19.826+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=run_dbt, task_id=run_dbt_all_models, run_id=manual__2025-04-18T19:56:57.798037+00:00, execution_date=20250418T195657, start_date=20250418T220340, end_date=20250418T220419
[2025-04-18T22:04:19.877+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T22:04:19.884+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 666 for task run_dbt_all_models (Bash command failed. The command returned a non-zero exit code 1.; 50760)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-18T22:04:19.939+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T22:04:19.983+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T22:04:19.987+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
