[2025-04-14T14:51:02.951+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T14:51:02.989+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_csv_to_bigquery.submit_spark_job manual__2025-04-14T14:50:58.793505+00:00 [queued]>
[2025-04-14T14:51:03.007+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_csv_to_bigquery.submit_spark_job manual__2025-04-14T14:50:58.793505+00:00 [queued]>
[2025-04-14T14:51:03.008+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-14T14:51:03.023+0000] {taskinstance.py:2890} INFO - Executing <Task(DataprocSubmitJobOperator): submit_spark_job> on 2025-04-14 14:50:58.793505+00:00
[2025-04-14T14:51:03.034+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_csv_to_bigquery', 'submit_spark_job', 'manual__2025-04-14T14:50:58.793505+00:00', '--job-id', '466', '--raw', '--subdir', 'DAGS_FOLDER/spark_job/spark_job.py', '--cfg-path', '/tmp/tmpicbu__q9']
[2025-04-14T14:51:03.037+0000] {standard_task_runner.py:105} INFO - Job 466: Subtask submit_spark_job
[2025-04-14T14:51:03.038+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-14T14:51:03.039+0000] {standard_task_runner.py:72} INFO - Started process 5404 to run task
[2025-04-14T14:51:03.095+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_csv_to_bigquery.submit_spark_job manual__2025-04-14T14:50:58.793505+00:00 [running]> on host b7be566335ce
[2025-04-14T14:51:03.184+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_csv_to_bigquery' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T14:50:58.793505+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T14:50:58.793505+00:00'
[2025-04-14T14:51:03.186+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T14:51:03.201+0000] {dataproc.py:2618} INFO - Submitting job
[2025-04-14T14:51:03.203+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-14T14:51:03.204+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud) shall not contain '_' according to RFC3986.
[2025-04-14T14:51:03.205+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-14T14:51:03.662+0000] {dataproc.py:2630} INFO - Job b5c61ac1-2f71-45ba-8bed-c18c22dfc36a submitted successfully.
[2025-04-14T14:51:03.682+0000] {dataproc.py:2665} INFO - Waiting for job b5c61ac1-2f71-45ba-8bed-c18c22dfc36a to complete
[2025-04-14T14:51:13.893+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2666, in execute
    self.hook.wait_for_job(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 560, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 861, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "db-project-456518"
  job_id: "b5c61ac1-2f71-45ba-8bed-c18c22dfc36a"
}
placement {
  cluster_name: "db-project-dataproc-cluster"
  cluster_uuid: "fbba43c0-2ff2-4103-a737-7b2688957d54"
}
pyspark_job {
  main_python_file_uri: "gs://db_project_data_bucket/code/main_spark.py"
}
status {
  state: ERROR
  details: "Job failed with message [ModuleNotFoundError: No module named \'pyspark.sql.function\']. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a?project=db-project-456518&region=europe-central2\ngcloud dataproc jobs wait \'b5c61ac1-2f71-45ba-8bed-c18c22dfc36a\' --region \'europe-central2\' --project \'db-project-456518\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/\ngs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/driveroutput.*"
  state_start_time {
    seconds: 1744642268
    nanos: 895321000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1744642260
    nanos: 36446000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1744642260
    nanos: 54750000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1744642260
    nanos: 285459000
  }
}
driver_output_resource_uri: "gs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/"
job_uuid: "b5c61ac1-2f71-45ba-8bed-c18c22dfc36a"
done: true

[2025-04-14T14:51:13.905+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=spark_csv_to_bigquery, task_id=submit_spark_job, run_id=manual__2025-04-14T14:50:58.793505+00:00, execution_date=20250414T145058, start_date=20250414T145102, end_date=20250414T145113
[2025-04-14T14:51:13.942+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T14:51:13.943+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 466 for task submit_spark_job (Job failed:
reference {
  project_id: "db-project-456518"
  job_id: "b5c61ac1-2f71-45ba-8bed-c18c22dfc36a"
}
placement {
  cluster_name: "db-project-dataproc-cluster"
  cluster_uuid: "fbba43c0-2ff2-4103-a737-7b2688957d54"
}
pyspark_job {
  main_python_file_uri: "gs://db_project_data_bucket/code/main_spark.py"
}
status {
  state: ERROR
  details: "Job failed with message [ModuleNotFoundError: No module named \'pyspark.sql.function\']. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a?project=db-project-456518&region=europe-central2\ngcloud dataproc jobs wait \'b5c61ac1-2f71-45ba-8bed-c18c22dfc36a\' --region \'europe-central2\' --project \'db-project-456518\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/\ngs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/driveroutput.*"
  state_start_time {
    seconds: 1744642268
    nanos: 895321000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1744642260
    nanos: 36446000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1744642260
    nanos: 54750000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1744642260
    nanos: 285459000
  }
}
driver_output_resource_uri: "gs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/"
job_uuid: "b5c61ac1-2f71-45ba-8bed-c18c22dfc36a"
done: true
; 5404)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2666, in execute
    self.hook.wait_for_job(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 560, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 861, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "db-project-456518"
  job_id: "b5c61ac1-2f71-45ba-8bed-c18c22dfc36a"
}
placement {
  cluster_name: "db-project-dataproc-cluster"
  cluster_uuid: "fbba43c0-2ff2-4103-a737-7b2688957d54"
}
pyspark_job {
  main_python_file_uri: "gs://db_project_data_bucket/code/main_spark.py"
}
status {
  state: ERROR
  details: "Job failed with message [ModuleNotFoundError: No module named \'pyspark.sql.function\']. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a?project=db-project-456518&region=europe-central2\ngcloud dataproc jobs wait \'b5c61ac1-2f71-45ba-8bed-c18c22dfc36a\' --region \'europe-central2\' --project \'db-project-456518\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/\ngs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/driveroutput.*"
  state_start_time {
    seconds: 1744642268
    nanos: 895321000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1744642260
    nanos: 36446000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1744642260
    nanos: 54750000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1744642260
    nanos: 285459000
  }
}
driver_output_resource_uri: "gs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-central2-1014201654849-u6eckw91/google-cloud-dataproc-metainfo/fbba43c0-2ff2-4103-a737-7b2688957d54/jobs/b5c61ac1-2f71-45ba-8bed-c18c22dfc36a/"
job_uuid: "b5c61ac1-2f71-45ba-8bed-c18c22dfc36a"
done: true

[2025-04-14T14:51:13.972+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T14:51:14.000+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T14:51:14.002+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
